### ISSUE TITLE
Python 3.10 pip install fails from conda-forge

### ISSUE THREAD

**Issue by Lswhiteh** [latchbio/latch#43] opened 2022-05-03 22:44 UTC
**Issue**: When creating a new conda (v4.12.0) environment with python=3.10 (conda-forge channel) pip fails to install latch. Untested on default channel at the moment. Looks like a dependency requires python < 3.9.

**Reproducibility**: Reproducible over multiple attempts with identical commands.

**Workaround**: Using python=3.8 (conda-forge) ends up with a fixed install process as expected. 

**Notes**: Conda channels listed below
```
$ conda config --show channels
channels:
  - conda-forge
  - defaults
  - bioconda
```

**Command**:
```{bash}
$ conda create -n latch-310 -c conda-forge python=3.10 -y
$ conda activate latch-310
$ pip install latch
```

**Trace**:
```
$ pip install latch
Collecting latch
  Using cached latch-0.7.1-py3-none-any.whl (49 kB)
Collecting boto3>=1.2
  Downloading boto3-1.22.6-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.5/132.5 KB 4.4 MB/s eta 0:00:00
Collecting typing-extensions==4.0.1
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting requests>=2.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting docker>=5.0
  Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)
Collecting tqdm>=4.63.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting flaightkit==0.2.0
  Using cached flaightkit-0.2.0-py3-none-any.whl (513 kB)
Collecting flaightkitplugins-pod==0.0.1
  Using cached flaightkitplugins-pod-0.0.1.tar.gz (2.7 kB)
  Preparing metadata (setup.py) ... done
Collecting pyjwt>=0.2.0
  Using cached PyJWT-2.3.0-py3-none-any.whl (16 kB)
Collecting pytz<2018.5,>=2017.2
  Using cached pytz-2018.4-py2.py3-none-any.whl (510 kB)
Collecting pyarrow<4.0.0,>=2.0.0
  Using cached pyarrow-3.0.0.tar.gz (682 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [272 lines of output]
      Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
      Collecting cython>=0.29
        Using cached Cython-0.29.28-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
      Collecting numpy==1.19.4
        Using cached numpy-1.19.4.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [246 lines of output]
            setup.py:67: RuntimeWarning: NumPy 1.19.4 may not yet support Python 3.10.
              warnings.warn(
            Running from numpy source directory.
            setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
              run_build = parse_setuppy_commands()
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_common.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/bit_generator.pyx
            Cythonizing sources
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            blis_info:
              libraries blis not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            openblas_info:
              libraries openblas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries tatlas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
              libraries satlas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries ptf77blas,ptcblas,atlas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            atlas_blas_info:
              libraries f77blas,cblas,atlas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            accelerate_info:
              NOT AVAILABLE
      
            /tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/system_info.py:1914: UserWarning:
                Optimized (vendor) Blas libraries are not found.
                Falls back to netlib Blas library which has worse performance.
                A better performance should be easily gained by switching
                Blas library.
              if self._calc_info(blas):
            blas_info:
              libraries blas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            /tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/system_info.py:1914: UserWarning:
                Blas (http://www.netlib.org/blas/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [blas]) or by setting
                the BLAS environment variable.
              if self._calc_info(blas):
            blas_src_info:
              NOT AVAILABLE
      
            /tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/system_info.py:1914: UserWarning:
                Blas (http://www.netlib.org/blas/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [blas_src]) or by setting
                the BLAS_SRC environment variable.
              if self._calc_info(blas):
              NOT AVAILABLE
      
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
              libraries mkl_rt not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            openblas_lapack_info:
              libraries openblas not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            openblas_clapack_info:
              libraries openblas,lapack not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            flame_info:
              libraries flame not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries tatlas,tatlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries tatlas,tatlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries tatlas,tatlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries tatlas,tatlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE
      
            atlas_3_10_info:
              libraries lapack_atlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries satlas,satlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries satlas,satlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries satlas,satlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries satlas,satlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE
      
            atlas_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries ptf77blas,ptcblas,atlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE
      
            atlas_info:
              libraries lapack_atlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries f77blas,cblas,atlas not found in /home/lswhiteh/miniconda3/envs/latch-310/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries f77blas,cblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries f77blas,cblas,atlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries f77blas,cblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE
      
            lapack_info:
              libraries lapack not found in ['/home/lswhiteh/miniconda3/envs/latch-310/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
              NOT AVAILABLE
      
            /tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/system_info.py:1748: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
            lapack_src_info:
              NOT AVAILABLE
      
            /tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/system_info.py:1748: UserWarning:
                Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                the LAPACK_SRC environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
              NOT AVAILABLE
      
            numpy_linalg_lapack_lite:
              FOUND:
                language = c
                define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
      
            /tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running dist_info
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.linux-x86_64-3.10
            creating build/src.linux-x86_64-3.10/numpy
            creating build/src.linux-x86_64-3.10/numpy/distutils
            building library "npymath" sources
            Could not locate executable gfortran
            Could not locate executable f95
            Could not locate executable ifort
            Could not locate executable ifc
            Could not locate executable lf95
            Could not locate executable pgfortran
            Could not locate executable nvfortran
            Could not locate executable f90
            Could not locate executable f77
            Could not locate executable fort
            Could not locate executable efort
            Could not locate executable efc
            Could not locate executable g77
            Could not locate executable g95
            Could not locate executable pathf95
            Could not locate executable nagfor
            don't know how to compile Fortran code on platform 'posix'
            Traceback (most recent call last):
              File "/tmp/tmpb5jpcxz8_in_process.py", line 363, in <module>
                main()
              File "/tmp/tmpb5jpcxz8_in_process.py", line 345, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/tmp/tmpb5jpcxz8_in_process.py", line 164, in prepare_metadata_for_build_wheel
                return hook(metadata_directory, config_settings)
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
                self.run_setup()
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
                super(_BuildMetaLegacyBackend,
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 508, in <module>
                setup_package()
              File "setup.py", line 500, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 165, in setup
                return distutils.core.setup(**attrs)
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 31, in run
                egg_info.run()
              File "/tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/command/egg_info.py", line 24, in run
                self.run_command("build_src")
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/tmp/pip-build-env-xdp5zrn7/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/command/build_src.py", line 155, in build_sources
                self.build_library_sources(*libname_info)
              File "/tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/command/build_src.py", line 288, in build_library_sources
                sources = self.generate_sources(sources, (lib_name, build_info))
              File "/tmp/pip-install-n8jktqo3/numpy_3fd26ec7565745e2969e1d9bbe8b7458/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 663, in get_mathlib_info
                raise RuntimeError("Broken toolchain: cannot link a simple C program")
            RuntimeError: Broken toolchain: cannot link a simple C program
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by SSP231211** [comment] 2022-05-25 14:48
I think the problem is mentioned in this line : Ignoring numpy: markers 'python_version < "3.9"' don't match your environment.

I was also getting the same error, the error was because of incompatibility of latest python version 3.10 with latch , because latch supported by the python versions less than 3.9.0. That's why I uninstalled latest version 3.10 and installed python 3.8.9 using link https://www.python.org/downloads/release/python-389/ and it worked well.

**Comment by ayushkamat** [comment] 2022-09-08 19:29
Yes, the root of the problem is that latch doesn't officially support python >3.9. Closing for now.

**Closed by ayushkamat** 2022-09-08 19:29 UTC
