### ISSUE TITLE
urrlib3

### ISSUE THREAD

**Issue by GeOdette** [latchbio/latch#97] opened 2022-07-02 22:31 UTC
I get this error 
```
"RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```
Okay I solve it with "pip install --upgrade requests==2.20.1" but I have to do this for all workflows.

**Comment by ayushkamat** [comment] 2022-08-01 22:14
Closing as I am unable to reproduce

**Closed by ayushkamat** 2022-08-01 22:14 UTC
