### ISSUE TITLE
Better error when the user uses a task that's too small

### ISSUE THREAD

**Issue by hannahle** [latchbio/latch#166] opened 2022-09-10 17:59 UTC
A user was running a _salmon_ task on a @small_task.

No errors were thrown. The task simply ended with a "Success" status, which is confusing. 

Insufficient task size should return a more semantic error in task logs.

**Comment by kennyworkman** [comment] 2022-12-19 02:02
If a task fails due to lack of resources I can confirm that it will not show a "Success" status.

Closing because this has been around for a while and is vague

**Closed by kennyworkman** 2022-12-19 02:02 UTC
Labels: enhancement
